### ISSUE TITLE
reduce image display time/memory for Juno and IJulia

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageShow.jl#11]
This is tested in a remote IJulia (100M LAN network), similar results can be observed from local Juno and IJulia. (this situation doesn't show in terminal REPL)

```julia
using TestImages
img = testimage("cameraman")
@time display(img)
@time display(img)
# 5.357775 seconds (9.10 M allocations: 544.977 MiB, 4.70% gc time)
# 2.960242 seconds (3.68 M allocations: 290.248 MiB, 11.38% gc time)
```

```julia
using TestImages, ImageShow
img = testimage("cameraman")
@time display(img)
@time display(img)
# 3.167470 seconds (8.06 M allocations: 404.792 MiB, 6.76% gc time)
# 0.128455 seconds (9.60 k allocations: 1.644 MiB)
```

Also, there's a significant network traffic if not using `ImageShow` (if using `ImageShow` the out traffic is at most 350Kb)

<img src="https://user-images.githubusercontent.com/8684355/57512502-6ae3ee80-733e-11e9-82b6-cb4cce2f3792.png" width="150" height="400" />

as a comparision,
```julia
# terminal REPL
using TestImages
img = testimage("cameraman")
@time display(img)
@time display(img)
# 0.616769 seconds (1.77 M allocations: 86.887 MiB, 3.71% gc time)
# 0.031414 seconds (72.89 k allocations: 2.940 MiB)
```

Any ideas what might cause this problem?

**Comment by RalphAS** [comment]
I believe the extra traffic arises because the default image presentation from Juno/IJulia is via SVG. The main point of this package is to switch to PNG instead, which is much faster for showing dense images (locally or remotely). I presume there is a reason for the SVG default, but I have not seen it documented.

TestImages and similar packages depend on ImageCore and FileIO; the latter invokes ImageMagick or QuartzImageIO as needed.

It was a design decision to make ImageCore as lightweight as reasonably possible, and FileIO is just a shell, so neither of them should depend on ImageShow.

One option is to have ImageMagick and QuartzImageIO depend on ImageShow.

A fallback is to have a Requires.jl clause in ImageCore so that if Juno or IJulia is loaded, then ImageShow is imported too. Unfortunately Pkg doesn't fully understand Requires, so that might generate annoying messages.

**Comment by johnnychen94** [comment]
@kimikage can we close this issue?

**Comment by kimikage** [comment]
If you are satisfied with the measures in Colors.jl, you can.
