### ISSUE TITLE
Display time series as GIFs or image sequences?

### ISSUE THREAD

**Issue by tlnagy** [JuliaImages/ImageShow.jl#22]
https://github.com/timholy/Images.jl/issues/554 made me think that it might be nice to show time series data as GIFs or as a horizontal sequence (show a couple frames then an ellipsis). Currently master simply shows like this

``` julia
Gray Images.Image with:
  data: 2048×2044×2 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},3}
  properties:
    timedim: 3
    colorspace: Gray
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
```

Maybe this is a bad idea and the text output is better. Thought I would put it out there anyway.

**Comment by timholy** [comment]
Even a non-temporal image sometimes makes sense as a looping image. For example if you're showing a 3d stack of microscopy images, for me it's easier to mentally assemble the structure if the changes occur "in place" rather than me having to determine corresponding points across mosaic tiles. But this may be a matter of personal preference.

**Comment by johnnychen94** [comment]
Please try out the `play`/`explore`/`gif` functions in ImageShow 0.3 🚀
