### ISSUE TITLE
Include more functionality such as displaying an array as `Gray` color

### ISSUE THREAD

**Issue by roflmaostc** [JuliaImages/ImageShow.jl#55]
Hi all!

as discussed on Slack with @mkitti and @johnnychen94 we could include an `simshow` (simple show) to show inline graphics in Pluto and Jupyter.

A draft is like here: https://github.com/roflmaostc/SimpleImageView.jl

```julia
function simshow(arr::AbstractArray{<:Real}; 
                 set_one=true, set_zero=false,
                 f = identity,
                 γ = 1)

    arr = set_zero ? arr .- minimum(arr) : arr
    arr = set_one ? arr ./ maximum(arr) : arr

    arr = f(arr) 

    if !isone(γ)
        arr .= arr .^ γ
    end

    Gray.(arr)
end
```

Should I prepare a PR for including the functionality to this package?

I can also try to include RGB for 3D arrays.

Best,

Felix

**Comment by roflmaostc** [comment]
Based in ColorSchemes.jl we could also use different colormaps, e.g. `simshow(arr, cmap=:tableau_colorblind)`

Would it be ok to introduce that dependency?

**Comment by johnnychen94** [comment]
I'm supportive of having an explicit method (that doesn't get implicitly called by `Base.show`) to support various usages, it might need some experiments to shape out a good entry point that supports as many scenarios as possible. Since this is a visualization helper tool that won't be used in multi-threaded scenarios (I think?), I'm also supportive of having a global variable to control the default behavior.

Also cc @tlnagy who opened #41 and #43, maybe he's more interested in this.

**Comment by roflmaostc** [comment]
`imshow`is already used by ImageView.jl 😅
